import sys

sys.path.insert(0, "")
from src.domain.canva import CanvasRepository, Canva
from src.domain.user import UserRepository, User

database_path = "data/database.db"


canva = Canva(
    id="canva-1",
    name="unicorn",
    width=8,
    height=8,
    user_id="user-ainhoa",
    pixels=[
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
        "#2D98FA",
        "#585FD6",
        "#9658ED",
        "#C745D6",
        "#FA3E78",
        "#FA3E78",
        "#C745D6",
        "#9658ED",
        "#585FD6",
        "#2D98FA",
    ],
)
canva_two = Canva(
    id="canva-2",
    name="creep",
    width=8,
    height=8,
    user_id="user-gabriel",
    pixels=[
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "#141414",
        "#121212",
        "green",
        "green",
        "#141414",
        "#141414",
        "green",
        "green",
        "green",
        "green",
        "#141414",
        "#121212",
        "green",
        "green",
        "#141414",
        "#141414",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "#141414",
        "#141414",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "#141414",
        "green",
        "green",
        "#141414",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "#141414",
        "green",
        "green",
        "#141414",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
        "green",
    ],
)
canvas_repository = CanvasRepository(database_path)
canvas_repository.save(canva)
canvas_repository.save(canva_two)


user_one = User(
    id="user-ainhoa", name="ainhoa", email="ainhoa@example.es", password="aguacate"
)
user_two = User(
    id="user-gabriel", name="an3xo", email="petin@example.es", password="petin"
)
user_repository = UserRepository(database_path)
user_repository.save(user_one)
user_repository.save(user_two)
print("Base de datos inicializada en " + database_path)
